export const BACKGROUND_COLOR = '#ffffff'
export const DEFAULT_COLOR = '#ffffff'
export const DEFAULT_COLOR_2 = '#FF0000'
export const KEY_STORAGE = 'com.kontranik.mosaiccrochetpattern.state'
export const VERSION = '1.1.2'
export const UNKNOWN_NAME = 'unnamed pattern'
